PUT http://localhost:8082/account/watchlist
Content-Type: application/json

{
  "symbols": [
    {
      "value": "AAPL"
    },
    {
      "value": "GOOGL"
    },
    {
      "value": "MSFT"
    }
  ]
}